site:
  title: LOCAL DataStax Streaming Docs
  start_page: streaming::index.adoc
  url: https://docs.datastax.com/en

content:
  sources:
    # DATASTAX STREAMING DOCUMENTATION MAIN PAGE
    - url: streaming-site
      start_path: site-main
      branches: 
        - draft #not versioned
      tags: 
        - streaming

    # LUNA STREAMING DOCUMENTATION SITE
    - url: pulsar-docs
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches: 
        - v*-draft #all draft versions
      tags: 
        - streaming
        - luna-streaming

    # ASTRA STREAMING DOCUMENTATION SITE
    - url: astra-streaming-docs
      branches: 
        - v*-draft #all draft versions
      tags:
        - streaming
        - astra-streaming
    
    # PULSAR LEARNING SITE
    - url: learning
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches: 
        - draft #not versioned
      tags: 
        - streaming
        - learning

    - url: starlight-for-kafka-docs
      branches:
        - v*-draft #all draft versions
      tags:
        - streaming
        - kafka

    - url: starlight-for-rabbitmq-docs
      branches:
        - v*-draft #all draft versions
      tags:
        - streaming
        - rabbitmq

    - url: starlight-for-jms-docs
      branches:
        - v*-draft #all draft versions
      tags:
        - streaming
        - jms

runtime:
  log:
    level: info
    failure_level: error

asciidoc:
  attributes:
    source-highlighter: highlightjs
    page-pagination: ''
    sectanchors: ''
    sectlinks: ''
    id-prefix: ''
    id-separator: '-'

  extensions:
    - streaming-site/lib/tabs-block.js

ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: streaming-site/supplemental-ui

output:
  dir: _build # added the underscore so it will be top dir in the tree