name: Docsbot Command
on:
  repository_dispatch:
    types:
      - docsbot-command
      - docbot-command
jobs:
  ProcessBotCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Add seen reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: seen

      - name: Environment
        if: github.event.client_payload.slash_command.args.named.log-level == 'debug'
        run: env

      - name: Client payload context
        if: github.event.client_payload.slash_command.args.named.log-level == 'debug'
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "${PAYLOAD_CONTEXT}"

      - name: Create URL to the run output
        id: runUrl
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Validate command
        id: validate
        run: |
          cmd="${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}";
          [[ -z "${cmd}" ]] && { echo "error-message=You didn't provide a command" >> $GITHUB_OUTPUT; exit 1; }
          
          array=("ping" "stage");
          [[ ! " ${array[*]} " =~ " ${cmd} " ]] && { echo "error-message=I don't know what the command \"${cmd}\" means" >> $GITHUB_OUTPUT; exit 1;}
          
          exit 0;

      - name: Process command
        id: process
        if: ${{ success() }}
        uses: peter-evans/repository-dispatch@v2
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        with:
          event-type: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
          client-payload: ${{ env.PAYLOAD_CONTEXT }}

      - name: Add confused reaction
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ failure() }}
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: confused
          body: |
            > ${{ steps.validate.outputs.error-message }}
            > ${{ steps.process.outputs.error-message }}
            
            [Here's what happened](${{ steps.runUrl.outputs.run-url }})