name: Docsbot Command
on:
  repository_dispatch:
    types:
      - docsbot-command
      - docbot-command
jobs:
  ProcessBotCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Add seen reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: seen

      - name: Environment
        if: github.event.client_payload.slash_command.args.named.log-level == 'debug'
        run: env

      - name: Client payload context
        if: github.event.client_payload.slash_command.args.named.log-level == 'debug'
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      - name: Validate command
        id: validate
        run: |
          [[ -z "${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}" ]] && { echo "error-message=You didn't provide a command" >> $GITHUB_OUTPUT; exit 1; }

      - name: Process command
        id: process
        if: ${{ success() }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
          client-payload: ${{ github.event.client_payload }}

#      - name: Create URL to the run output
#        id: vars
#        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
#
#      - name: Add reaction
#        uses: peter-evans/create-or-update-comment@v2
#        if: not steps.process.outputs.error-message
#        with:
#          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
#          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
#          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
#          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
#          body: |
#            Hello @${{ github.event.client_payload.github.actor }}!
#
#            [Click here to see the command run output][1]
#
#            [1]: ${{ steps.vars.outputs.run-url }}

      - name: Add hooray reaction
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ success() }}
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Add confused reaction
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ failure() }}
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: confused
          body: |
            > ${{ steps.validate.outputs.error-message }}
            > ${{ steps.process.outputs.error-message }}