#Create a workflow dispatch event
#https://docs.github.com/en/enterprise-cloud@latest/rest/actions/workflows#create-a-workflow-dispatch-event
#
#curl \
#  -X POST \
#  -H "Accept: application/vnd.github+json" \
#  -H "Authorization: Bearer <YOUR-TOKEN>" \
#  https://api.github.com/repos/ddieruf/streaming-site/actions/workflows/docsbot-command.yml/dispatches \
#  -d '{"ref":"main","inputs":{"repository":"ddieruf/learning","comment-id":"1317416117","cmd":"ping","log-level":"info"}}'

name: Docsbot Command
on:
  workflow_dispatch:
    inputs:
      log-level:
        required: false
        type: choice
        options:
          - info
          - error
        default: error
        description: "How chatty is docsbot"
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: false
      comment-id:
        description: 'The comment-id of the slash command'
        required: false
      cmd:
        required: true
        type: choice
        options:
          - ping
          - stage
        default: ping
        description: "What command docsbot should execute"
      doc-name:
        required: false
        type: string
        description: "The bsys document name"
      staging-server:
        required: false
        type: choice
        options:
          - preview
          - coppi
          - merckx
          - hinault
        default: "preview"
        description: "The server to use for staging a site"
      npm-script:
        required: false
        type: string
        default: "build:prod"
        description: "The npm script to use to build the site"
jobs:
  PrintContext:
    if: github.event.inputs.log-level == 'info'
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

  AddSeenReaction:
    if: github.event.inputs.comment-id
    uses: ddieruf/streaming-site/.github/workflows/update-issue-comment.yml@draft
    secrets: inherit
    with:
      reaction-type: eyes

  ProcessPingCommand:
    if: github.event.inputs.cmd == 'ping'
    uses: ddieruf/streaming-site/.github/workflows/ping-command.yml@draft
    secrets: inherit

  ProcessStagingCommand:
    if: github.event.inputs.cmd == 'stage'
    uses: ddieruf/streaming-site/.github/workflows/stage-command.yml@draft
    secrets: inherit
    with:
      scripsi-token: ${{ secrets.ddieruf }}

#  UpateCommentWithError:
#    uses: ./.github/workflows/update-issue-comment.yml
#    secrets: inherit
#    needs: ProcessBotCommand
#    if: failure() && github.event.inputs.comment-id
#    with:
#      event: ${{ toJson(github.event) }}
#      reaction-type: confused
#      message: |
#        > ${{ needs.AddSeenReaction.outputs.error-message }}
#
#        [Here's what happened](${{ needs.AddSeenReaction.outputs.run-url }})