name: Docsbot Command
on:
  repository_dispatch:
    types:
      - docsbot-command
      - docbot-command
jobs:
  ProcessBotCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env

      - name: Client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      - name: Create URL to the run output
        id: vars
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            
            [Click here to see the command run output][1]
            
            [1]: ${{ steps.vars.outputs.run-url }}


#      - name: Update comment
#        uses: peter-evans/create-or-update-comment@v2
#        with:
#          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
#          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
#          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
#          body: |
#            Hello @${{ github.event.client_payload.github.actor }}!
#
#            [Click here to see the command run output][1]
#
#            [1]: ${{ steps.vars.outputs.run-url }}

#      - name: Create comment
#        uses: peter-evans/create-or-update-comment@v2
#        with:
#          token: ${{ secrets.PAT }}
#          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
#          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
#          body: |
#            [Command run output][1]
#
#            [1]: ${{ steps.vars.outputs.run-url }}