name: Ping Command
on:
  repository_dispatch:
    types: [ping]

jobs:
  PingCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        if: github.event.client_payload.slash_command.args.named.log-level == 'debug'
        run: env

      - name: Client payload context
        if: github.event.client_payload.slash_command.args.named.log-level == 'debug'
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      - name: Add hooray reaction
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ success() }}
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          body: |
            > Hi @${{ github.event.client_payload.github.actor }}. Pong.