name: Ping Command

on:
  workflow_call:
    inputs:
      event:
        required: true
        type: string
    secrets:
      DOCSBOT_ACTION_TOKEN:
        required: true

jobs:
  PingCommand:
    runs-on: ubuntu-latest
    steps:
      - if: fromJSON(inputs.event).inputs.comment-id == ''
        run: exit 1

      - if: fromJSON(inputs.event).inputs.repository == ''
        run: exit 1

      - name: Add hooray reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ fromJSON(inputs.event).inputs.repository }}
          comment-id: ${{ fromJSON(inputs.event).inputs.comment-id }}
          reaction-type: hooray
          body: |
            > Hi @${{ fromJSON(inputs.event).sender.login }}. Pong.