name: Ping Command
on:
  repository_dispatch:
    types: [ping]

jobs:
  PingCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        if: github.event.client_payload.slash_command.args.named.log-level == 'debug'
        run: env

      - name: Client payload context
        if: github.event.client_payload.slash_command.args.named.log-level == 'debug'
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: echo "message=pong ${{ github.event.client_payload.slash_command.args.all }}" >> $GITHUB_OUTPUT