name: Stage site

on:
  workflow_call:
    inputs:
      doc-name:
        required: true
        type: string
      scripsi-repo:
        required: true
        type: string
      scripsi-ref:
        required: true
        type: string
      staging-server:
        required: true
        type: string
    secrets:
      scripsi-token:
        required: true
      AWS_OVPN:
        required: true

jobs:
  BuildSite:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        #working-directory: ${{ github.workspace }}/scripsi/bsys
    steps:
#      - name: Checkout scripsi
#        uses: actions/checkout@v3
#        with:
#          repository: ${{ inputs.scripsi-repo }}
#          ref: ${{ inputs.scripsi-ref }}
#          token: ${{ secrets.scripsi-token }}
#          path: ${{ github.workspace }}/scripsi
#
#      - name: Download bsys artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: bsys-0.3.1.tar.gz
#          path: ${{ github.workspace }}/scripsi/bsys/dist
#
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.9'
#
#      - name: Install bsys
#        run: pip install --upgrade ./dist/bsys-0.3.1.tar.gz

      # =======================================================
      # ESTABLISH VPN CONNECTION
      # =======================================================
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn

      # Ref: https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-working-endpoint-export.html
      - name: Setup VPN config
        run: |
          echo "${{ secrets.AWS_OVPN }}" > $GITHUB_WORKSPACE/client.ovpn

      - name: Open VPN connection
        run: sudo openvpn --config "$GITHUB_WORKSPACE/client.ovpn" --log "$GITHUB_WORKSPACE/vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until ping -c1 "${{ inputs.staging-server }}"; do sleep 2; done

      # =======================================================
      # DEPLOY
      # =======================================================
#      - name: Deploy site
#        id: buildSite
#        if: success()
#        working-directory: ${{ github.workspace }}/scripsi/bsys
#        run: |
#          bsys lsd
#          # bsys deploy ${{ inputs.doc-name }} ${{ inputs.staging-server }} |& tee $GITHUB_WORKSPACE/bsys-deploy.log

      # =======================================================
      # CLEAN UP
      # =======================================================
      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 $GITHUB_WORKSPACE/vpn.log
          sudo killall $GITHUB_WORKSPACE/openvpn

      - name: Upload VPN logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: VPN-logs
          path: ${{ github.workspace }}/vpn.log

#      - name: Upload bsys deploy logs
#        uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: bsys-deploy-logs
#          path: ${{ github.workspace }}/bsys-deploy.log