name: Stage Command
on:
  workflow_call:
    inputs:
      comment-id:
        required: false
        type: string
      doc-name:
        required: true
        type: string
      npm-script:
        required: true
        type: string
      staging-server:
        required: true
        type: string
    secrets:
      ddieruf:
        required: true
      AWS_OVPN:
        required: true

jobs:
  AddBuildBsysStatus:
    if: github.event.inputs.comment-id
    uses: ddieruf/streaming-site/.github/workflows/update-issue-comment.yml@draft
    secrets: inherit
    with:
      message: |
        > Building bsys

  BuildBsys:
    uses: ddieruf/streaming-site/.github/workflows/build-bsys.yml@draft
    secrets:
      scripsi-token: ${{ secrets.ddieruf }}
    with:
      scripsi-repo: "ddieruf/scripsi"
      scripsi-ref: "testing-workflow"

  AddBuildSiteStatus:
    if: github.event.inputs.comment-id
    uses: ddieruf/streaming-site/.github/workflows/update-issue-comment.yml@draft
    secrets: inherit
    with:
      message: |
        > Building ${{ inputs.doc-name }}

  BuildDocsSite:
    needs: BuildBsys
    uses: ddieruf/streaming-site/.github/workflows/build-site.yml@draft
    secrets:
      scripsi-token: ${{ secrets.ddieruf }}
      antora-github-token: ${{ secrets.ddieruf }}
    with:
      scripsi-repo: "ddieruf/scripsi"
      scripsi-ref: "testing-workflow"
      antora-github-username: "ddieruf"
      doc-name: ${{ inputs.doc-name }}
      npm-script: ${{ inputs.npm-script }}

  AddStageSiteStatus:
    if: github.event.inputs.comment-id
    uses: ddieruf/streaming-site/.github/workflows/update-issue-comment.yml@draft
    secrets: inherit
    with:
      message: |
        > Staging site

  StageDocsSite:
    needs: BuildDocsSite
    uses: ddieruf/streaming-site/.github/workflows/stage-site.yml@draft
    secrets:
      scripsi-token: ${{ secrets.ddieruf }}
      AWS_OVPN: ${{ secrets.AWS_OVPN }}
    with:
      scripsi-repo: "ddieruf/scripsi"
      scripsi-ref: "testing-workflow"
      doc-name: ${{ inputs.doc-name }}
      staging-server: ${{ inputs.staging-server }}

  AddSuccessReaction:
    if: github.event.inputs.comment-id && success()
    needs: StageDocsSite
    uses: ddieruf/streaming-site/.github/workflows/update-issue-comment.yml@draft
    secrets: inherit
    with:
      reaction-type: horray
      message: |
        > Success

  AddFailReaction:
    if: github.event.inputs.comment-id && failure()
    uses: ddieruf/streaming-site/.github/workflows/update-issue-comment.yml@draft
    secrets: inherit
    with:
      reaction-type: confused
      message: |
        > Failed