name: Stage Command
on:
  repository_dispatch:
    types: [stage]

jobs:
  StageCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Create URL to the run output
        id: runUrl
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Validate command
        id: validate
        run: |
          
          exit 0;

      - name: Checkout scripsi
        uses: actions/checkout@v3
        with:
          repository: 'ddieruf/scripsi'
          ref: 'new-features-for-streaming'
          token: ${{ secrets.ddieruf }}
          path: 'scripsi'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run bsys command
        id: bsysCmd
        run: |
          ls $GITHUB_WORKSPACE/scripsi
          #python ./scripsi/bsys/setup.py sdist bdist_wheel
          #pip install
          
          #bsys --automated \
          #  --verbose \
          #  --npmScriptName "build:prod" \
          #  --githubUsername "${{ github.event.client_payload.github.actor }}" \
          #  --githubToken "xxxxx" \
          #  build \
          #  datastaxStreaming
          
          #bsys stage datastaxStreaming preview

      - name: Add hooray reaction
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ success() }}
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          body: |
            > Your changes have been staged.
            > ${{ steps.bsysCmd.outputs.message }}

      - name: Add confused reaction
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ failure() }}
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: confused
          body: |
            > There was an error
            
            [Here's what happened](${{ steps.runUrl.outputs.run-url }})