name: Stage Command
on:
  repository_dispatch:
    types: [stage]

jobs:
  StageCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Create URL to the run output
        id: runUrl
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Validate command
        id: validate
        run: |
          docName="${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}"
          [[ -z "${docName}" ]] && { echo "error-message=Please provide a doc name as the second argument" >> $GITHUB_OUTPUT; exit 1; }
          exit 0;

      - name: Checkout scripsi
        uses: actions/checkout@v3
        with:
          repository: 'ddieruf/scripsi'
          ref: 'testing-workflow'
          token: ${{ secrets.ddieruf }}
          path: 'scripsi'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add installing message
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Building & installing bsys package

      - name: Install bsys
        id: installBsys
        run: |
          cd $GITHUB_WORKSPACE/scripsi/bsys
          
          echo "Building bsys"
          python setup.py sdist bdist
          
          echo "Installing bsys"
          pip install --upgrade ./dist/bsys-0.3.1.tar.gz

      - name: Add building message
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Building the site

      - name: Build site
        id: buildSite
        run: |
          cd $GITHUB_WORKSPACE/scripsi/bsys
          docName="${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}"

          #bsys -h
          #bsys lsd
          bsys --automated \
            --verbose \
            --npmScriptName "build:prod" \
            --githubUsername "${{ github.event.client_payload.github.actor }}" \
            --githubToken "${{ secrets.ddieruf }}" \
            build \
            ${docName}

      - name: Add staging message
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Staging the site

      - name: Stage site
        id: stageSite
        run: |
          cd $GITHUB_WORKSPACE/scripsi/bsys
          #bsys stage datastaxStreaming preview

      - name: Add hooray reaction
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ success() }}
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          body: |
            > Your changes have been staged
            > ${{ steps.bsysCmd.outputs.message }}

      - name: Add confused reaction
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ failure() }}
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: confused
          body: |
            > There was an error
            
            [Here's what happened](${{ steps.runUrl.outputs.run-url }})