name: Add message to comment

on:
  workflow_call:
    inputs:
      event:
        required: true
        type: string
      message:
        required: false
        type: string
      reaction-type:
        required: false
        type: string
    secrets:
      DOCSBOT_ACTION_TOKEN:
        required: true

jobs:
  AddMessageToComment:
    runs-on: ubuntu-latest
    steps:
      - name: Add message to comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
          repository: ${{ fromJSON(inputs.event).inputs.repository }}
          comment-id: ${{ fromJSON(inputs.event).inputs.comment.id }}
          reaction-type: ${{ inputs.reaction-type }}
          body: ${{ inputs.message }}
#
#      - name: Add reaction
#        uses: peter-evans/create-or-update-comment@v2
#        with:
#          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
#          repository: ${{ github.event.inputs.repository }}
#          comment-id: ${{ github.event.inputs.comment-id }}
#          reaction-type: hooray